/**
 * Sol mural language: real profiles lead a selective, evidence-based founders story with room for people, provenance, and the club's values.
 */
import { AnimatePresence, motion } from "framer-motion";
import { ArrowUpRight, X } from "lucide-react";
import { useState } from "react";
import { MagneticButton } from "@/components/MagneticButton";
import { WaveDivider } from "@/components/WaveDivider";

const story = "Sol Squash didn't start with a business plan. It started with a sport that changed two lives — and a shared belief that squash deserves a real home in Miami. We're Bruna and Vini, co-founders, professional squash players, and partners in life. We met at a squash tournament in Brazil in 2015, moved to London together, competed on the PSA World Tour, and coached players of all levels across the UK, Europe, and the USA. After years of living the sport from every angle — as athletes, coaches, and builders — we decided it was time to create the club we always wished existed. That club is Sol. A place where squash meets community, where every level is welcome, and where walking through the door feels like something. We wanted to share squash through our eyes — the joy, the challenge, the connection. Seeing people fall in love with this sport the way we did is what drives everything we do at Sol. — Bruna & Vini, Co-Founders";
const howItStarted = "From Brazil to London to Little River. Vini picked up a racket at 7 years old and never put it down. Self-taught from the start, he turned professional, represented the Brazilian National Team for years, reached a career-high world ranking of #132, and won bronze at the 2011 Pan American Games in Guadalajara. He built over two decades of coaching experience alongside his playing career, reaching the final of the PSA World Tour event in Moscow in 2018. Squash isn't something he does. It's who he is. Subbotnik PSA Open — Moscow, 2018. Pan American Games Bronze — Guadalajara, 2011. Bruna came to squash later — but when she did, she went all in. After graduating from university in London, she returned to Brazil and walked into a squash tournament where she met Vini. He became her coach. She turned professional, represented Brazil and Italy internationally, reached a career-high world ranking of #98, and competed at the PSA World Championships. They moved back to London together and built a life around the sport. PSA World Championships — 2021. Representing Brazil — South American Championships. Miami was the next chapter. A city full of energy, wellness culture, and racket sport players — but no real squash home. Having our own place had always been a shared dream. We wanted to share squash through our eyes and our mission. Squash is new in Miami, and while that's a challenge, it's also an incredible opportunity. We get to introduce a whole new generation to the most dynamic, rewarding sport we know. Building Sol — Little River, Miami.";

const profiles = [
  { name: "Bruna Petrillo", role: "Co-Founder & Squash Pro.", image: "/manus-storage/sol-bruna-profile_9b6e08d0.jpeg", bio: "PSA World Tour professional who represented Brazil and Italy internationally, competing at World Championships and earning international medals. She discovered squash as an adult and went all the way — which is exactly why she understands every stage of the journey. On court she brings energy, presence, and genuine connection. #98 World Ranking. PSA World Tour. 2 Nations. England Squash L2. US Squash Coach Pass. SafeSport Certified EN · PT." },
  { name: "Vinicius Rodrigues", role: "Co-Founder & Head Coach.", image: "/manus-storage/sol-vini-profile_e0ff7b8e.jpeg", bio: "PSA World Tour professional, Brazilian National Team member, Pan American Games bronze medalist, and PSA World Tour finalist. Self-taught from age 7, Vini started coaching early to fund his pro career — and what began as necessity became a true calling. On court, his natural habitat shows in every session. #132 World Ranking. 20+ Yrs Coaching. Pan Am Bronze 2011. WSF Level 2. US Squash L2. England Squash L2. SafeSport Certified EN · PT · ES." },
  { name: "Frida", role: "Chief Vibe Checker & Head of Court Security.", image: "/manus-storage/sol-frida-profile_cfa40671.jpeg", bio: "She's been part of this story since Brazil. She didn't have a choice, but she seems very happy about it. Frida has been with us since Brazil, survived the move to London, and now patrols the courts of Sol like she owns the place — which, honestly, she kind of does. She takes her naps very seriously and will not be disturbed. She loves chasing the squash ball and has been known to jump on court mid-session when she sees an opportunity she simply cannot ignore. She greets every single person who walks through the door. Always on duty. Do not disturb. Ball chaser. Official alarm. Pure Sol energy." },
];

const values = [
  ["Community First", "Everyone belongs here — from first-timers to competitive players. What matters is how you feel when you walk in."],
  ["Excellence on Court", "We've competed at the highest level. That standard shows up in every lesson, session, and interaction at Sol."],
  ["Genuine Care", "We truly connect with the people we work with. We're invested in your growth, on and off the court."],
  ["Squash for Miami", "Dynamic, challenging, endlessly fun — Miami is just getting started with this sport and we're here for all of it."],
];

export default function OurStory() {
  const [drawer, setDrawer] = useState<"story" | "start" | number | null>(null);
  const drawerContent = drawer === "story" ? { title: "OUR STORY", body: story } : drawer === "start" ? { title: "HOW IT STARTED", body: howItStarted } : typeof drawer === "number" ? { title: profiles[drawer].name, body: `${profiles[drawer].role} ${profiles[drawer].bio}` } : null;
  return (
    <>
      <section className="story-hero story-hero--real"><img className="story-hero__backdrop" src="/manus-storage/sol-team_28f84027.jpeg" alt="" aria-hidden="true" /><div className="story-hero__veil" /><div className="story-hero__layout"><figure className="story-hero__frame"><img src="/manus-storage/sol-team_28f84027.jpeg" alt="Bruna, Vini, and Frida together on a Sol squash court" /></figure><div className="story-hero__copy"><p className="eyebrow eyebrow--cyan">FROM BRAZIL TO LITTLE RIVER</p><h1>BUILT BY<br />PLAYERS.<br /><em>MADE FOR</em><br />EVERYONE.</h1><MagneticButton href="#" onClick={() => setDrawer("story")} className="button--mango">READ OUR STORY</MagneticButton></div></div></section>
      <p className="sr-only">{story}</p>
      <WaveDivider source="navy" destination="mango" />
      <section className="story-intro story-intro--real"><div><p className="eyebrow">THE JOURNEY</p><h2>FROM BRAZIL<br />TO LONDON.<br /><em>TO LITTLE RIVER.</em></h2></div><div><p>We met at a squash tournament in Brazil in 2015, moved to London together, competed on the PSA World Tour, and coached players of all levels across the UK, Europe, and the USA.</p><button className="story-detail-button" onClick={() => setDrawer("start")}>HOW IT STARTED <ArrowUpRight size={23} /></button></div></section>
      <p className="sr-only">{howItStarted}</p>
      <WaveDivider source="mango" destination="green" />
      <section className="credentials-section"><div className="credentials-section__heading"><p className="eyebrow eyebrow--cyan">ON COURT</p><h2>PSA WORLD<br />TOUR.<br /><em>COACHING.</em></h2><p>After years of living the sport from every angle — as athletes, coaches, and builders — we decided it was time to create the club we always wished existed.</p></div><div className="credentials-grid"><figure><img src="/manus-storage/sol-vini-match_ea7f6a9a.jpeg" alt="Vini competing on court" /></figure><figure><img src="/manus-storage/sol-bruna-medals_a77858ba.jpeg" alt="Bruna holding competition medals" /></figure></div></section>
      <WaveDivider source="green" destination="navy" />
      <section className="profiles-section profiles-section--real"><div className="profiles-section__heading"><p className="eyebrow eyebrow--cyan">THE PEOPLE WHO RUN THE RALLY</p><h2>MEET<br /><em>THE TEAM.</em></h2></div><div className="profile-list">{profiles.map((profile, index) => <article key={profile.name} className={`profile-card profile-card--${index}`} role="button" tabIndex={0} onClick={() => setDrawer(index)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); setDrawer(index); } }}><img src={profile.image} alt={profile.name} /><div className="profile-card__copy"><span>0{index + 1}</span><h3>{profile.name}</h3><p>{profile.role}</p><button onClick={(event) => { event.stopPropagation(); setDrawer(index); }}>READ BIO <ArrowUpRight size={21} /></button><p className="sr-only">{profile.bio}</p></div></article>)}</div></section>
      <WaveDivider source="navy" destination="green" />
      <section className="values-section values-section--real"><div className="values-section__top"><p className="eyebrow eyebrow--cyan">WHAT GUIDES US</p><h2>OUR <em>VALUES.</em></h2></div><div className="values-list">{values.map(([name, detail], index) => <motion.article key={name} initial={{ opacity: 0, y: 22 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * 0.07 }}><span>0{index + 1}</span><h3>{name}</h3><p>{detail}</p></motion.article>)}</div></section>
      <AnimatePresence>{drawerContent && <motion.aside className="story-drawer" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} aria-modal="true" role="dialog"><motion.div className="story-drawer__panel" initial={{ x: "100%" }} animate={{ x: 0 }} exit={{ x: "100%" }} transition={{ type: "spring", stiffness: 280, damping: 30 }}><button onClick={() => setDrawer(null)} aria-label="Close story drawer"><X size={27} /></button><span className="eyebrow">SOL SQUASH</span><h2>{drawerContent.title}</h2><p>{drawerContent.body}</p></motion.div></motion.aside>}</AnimatePresence>
    </>
  );
}
